CREATE OR REPLACE FUNCTION pljs_call_handler() RETURNS language_handler
AS 'MODULE_PATHNAME' LANGUAGE C;

CREATE OR REPLACE FUNCTION pljs_call_validator(oid) RETURNS void
	AS 'MODULE_PATHNAME' LANGUAGE C;

CREATE OR REPLACE FUNCTION pljs_inline_handler(internal) RETURNS void
  AS 'MODULE_PATHNAME' LANGUAGE C;

CREATE OR REPLACE TRUSTED LANGUAGE pljs
 HANDLER pljs_call_handler
 INLINE pljs_inline_handler
 VALIDATOR pljs_call_validator;

CREATE OR REPLACE FUNCTION pljs_version()
 RETURNS TEXT
 AS 'MODULE_PATHNAME', 'pljs_version'
 LANGUAGE C STRICT IMMUTABLE;

CREATE OR REPLACE FUNCTION pljs_info() RETURNS JSON
 AS 'MODULE_PATHNAME', 'pljs_info'
 LANGUAGE C;

CREATE OR REPLACE FUNCTION pljs_reset() RETURNS JSON
 AS 'MODULE_PATHNAME', 'pljs_reset'
 LANGUAGE C;

CREATE SCHEMA IF NOT EXISTS pljs;

CREATE TABLE IF NOT EXISTS pljs.modules (
  path TEXT PRIMARY KEY,
  source TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);

CREATE UNIQUE INDEX IF NOT EXISTS pljs_modules_path ON pljs.modules (path);
